BaiKiemTra02/BaiKiemTra02/Models/ErrorViewModel.cs
namespace BaiKiemTra02.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BaiKiemTra02/BaiKiemTra02/Models/LopHoc.cs
using System.ComponentModel.DataAnnotations;

namespace BaiKiemTra02.Models
{
    public class LopHoc
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string TenLopHoc { get; set; }
        [Required]
        public DateTime NamNhapHoc { get; set; } = DateTime.Now;
        [Required]
        public DateTime NamRaTruong { get; set; } = DateTime.Now;
        [Required]
        public int SoLuongSinhVien {  get; set; }   

    }
}

BaiKiemTra02/BaiKiemTra02/Controllers/HomeController.cs
using BaiKiemTra02.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BaiKiemTra02.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BaiKiemTra02/BaiKiemTra02/Controllers/LopHocController.cs
using BaiKiemTra02.Data;
using BaiKiemTra02.Models;
using Microsoft.AspNetCore.Mvc;

namespace BaiKiemTra02.Controllers
{
    public class LopHocController : Controller
    {
        private readonly ApplicationDbContext _db;
        public LopHocController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var lophoc = _db.LopHoc.ToList();
            ViewBag.LopHoc = lophoc;
            return View();
           
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(LopHoc lophoc)
        {
            if (ModelState.IsValid)
            {
                _db.LopHoc.Add(lophoc);            
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
      
      
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            var lophoc = _db.LopHoc.Find(id);
            return View(lophoc);
        }
        [HttpPost]
        public IActionResult Edit(LopHoc lophoc)
        {
            if (ModelState.IsValid)
            {
                _db.LopHoc.Update(lophoc);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            var theloai = _db.LopHoc.Find(id);
            return View(theloai);
        }


        [HttpPost]
        public IActionResult DeleteConfirm(int id)
        {
            var theloai = _db.LopHoc.Find(id);
            if (theloai == null)
            {
                return NotFound();
            }
            _db.LopHoc.Remove(theloai);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Detail(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            var theloai = _db.LopHoc.Find(id);
            return View(theloai);
        }
       
    }
}

BaiKiemTra02/BaiKiemTra02/Views/LopHoc/Create.cshtml
@{
    ViewData["Title"] = "Create";
}

@model LopHoc
<div class="container">
    <h3>Thêm Lớp học </h3>
    <div asp-validation-summary="All" class="text-danger"></div>
    <form method="post">
        <div class="form-group">
            <label asp-for="TenLopHoc">Tên lớp học</label>
            <input asp-for="TenLopHoc" type="text" class="form-control" />
            <span asp-validation-for="TenLopHoc" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="NamNhapHoc">Ngày nhập học</label>
            <input asp-for="NamNhapHoc" type="date" class="form-control" />
            <span asp-validation-for="NamNhapHoc" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="NamRaTruong">Ngày ra trường</label>
            <input asp-for="NamRaTruong" type="date" class="form-control" />
            <span asp-validation-for="NamRaTruong" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="SoLuongSinhVien">Số lượng sinh viên</label>
            <input asp-for="SoLuongSinhVien" type="text" class="form-control" />
            <span asp-validation-for="SoLuongSinhVien" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Tạo mới</button>
    </form>

</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BaiKiemTra02/BaiKiemTra02/Views/LopHoc/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
}

@model LopHoc
<div class="container">
    <h3>Thêm Lớp học </h3>
    <div asp-validation-summary="All" class="text-danger"></div>
    <form method="post">
        <div class="form-group">
            <label asp-for="TenLopHoc">Tên lớp học</label>
            <input asp-for="TenLopHoc" type="text" class="form-control" />
            <span asp-validation-for="TenLopHoc" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="NamNhapHoc">Ngày nhập học</label>
            <input asp-for="NamNhapHoc" type="date" class="form-control" />
            <span asp-validation-for="NamNhapHoc" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="NamRaTruong">Ngày ra trường</label>
            <input asp-for="NamRaTruong" type="date" class="form-control" />
            <span asp-validation-for="NamRaTruong" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="SoLuongSinhVien">Số lượng sinh viên</label>
            <input asp-for="SoLuongSinhVien" type="text" class="form-control" />
            <span asp-validation-for="SoLuongSinhVien" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Xóa</button>
        <a asp-action="Index" class="btn btn-secondary">Hủy</a>
    </form>

</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BaiKiemTra02/BaiKiemTra02/Views/LopHoc/Detail.cshtml
@model LopHoc

<div>
	ID: <b>@Model.Id</b> <br />
	Tên lớp học: <b>@Model.TenLopHoc</b> <br />
	Ngày nhập trường: <b>@String.Format("{00:dd/MM/yyyy}", Model.NamNhapHoc)</b> <br />
	Ngày ra trường: <b>@String.Format("{00:dd/MM/yyyy}", Model.NamRaTruong)</b> <br />
	Số lượng sinh viên: <b>@Model.SoLuongSinhVien</b> <br />
</div>

BaiKiemTra02/BaiKiemTra02/Views/LopHoc/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
}

@model LopHoc
<div class="container">
    <h3>Thêm Lớp học </h3>
    <div asp-validation-summary="All" class="text-danger"></div>
    <form method="post">
        <div class="form-group">
            <label asp-for="TenLopHoc">Tên lớp học</label>
            <input asp-for="TenLopHoc" type="text" class="form-control" />
            <span asp-validation-for="TenLopHoc" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="NamNhapHoc">Ngày nhập học</label>
            <input asp-for="NamNhapHoc" type="date" class="form-control" />
            <span asp-validation-for="NamNhapHoc" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="NamRaTruong">Ngày ra trường</label>
            <input asp-for="NamRaTruong" type="date" class="form-control" />
            <span asp-validation-for="NamRaTruong" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="SoLuongSinhVien">Số lượng sinh viên</label>
            <input asp-for="SoLuongSinhVien" type="text" class="form-control" />
            <span asp-validation-for="SoLuongSinhVien" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Cập nhật</button>
    </form>


    @section Scripts {
        @{
            <partial name="_ValidationScriptsPartial" />
        }
    }

BaiKiemTra02/BaiKiemTra02/Views/LopHoc/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<div class="container">
    <form asp-action="Search" method="get">
        <input type="text" name="searchString" placeholder="Nhập tên lớp cần tìm..." value="@ViewBag.SearchString" />
        <input type="submit" value="Tìm kiếm">
    </form>
    <table class="table">
        <thead>
        <th>Tên lớp học</th>
        <th>Năm nhập học </th>
        <th>Năm ra trường</th>
        <th>Số lượng sinh viên</th>
        </thead>
        <tbody>
            @foreach (var item in ViewBag.LopHoc)
            {
                <tr>
                    <td width="30%">
                        @item.TenLopHoc
                    </td>
                    <td width="40%">
                        <a asp-action="Edit" asp-route-id="@item.Id">
                            Edit
                        </a> |
                        <a asp-action="Detail" asp-route-id="@item.Id">
                            Detail
                        </a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">
                            Delete
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <a asp-controller="LopHoc" asp-action="Create" class="btn btn-primary">Thêm mới</a>
</div>